ShoraaDahak.Web/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Ganss.XSS;
using Microsoft.AspNetCore.Authorization;
using ShoraaDahak.Core.Services.Interfaces;
using ShoraaDahak.DataLayer.Models.Blog;
using ShoraaDahak.DataLayer.Models.Discussion;

namespace ShoraaDahak.Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly ICommentService _commentService;

        public BlogController(IBlogService blogService, ICommentService commentService)
        {
            _blogService = blogService;
            _commentService = commentService;
        }

        #region Index

        public IActionResult Index(int pageNum = 1, List<int> categories = null, string searchBlog = "")
        {
            ViewBag.PageNum = pageNum;
            int totalPage = (int)Math.Ceiling((decimal)_blogService.GetBlogsInBlogIndex().Count() / 9);
            ViewBag.totalPage = totalPage;

            return View(_blogService.GetBlogsInBlogIndex(pageNum, categories, searchBlog));
        }

        #endregion

        #region Detail Blog

        [Route("Blogs/{id}")]
        public IActionResult Blogs(int id)
        {
            Blog blog = _blogService.GetBlogForShowById(id);

            if (blog == null)
            {
                return NotFound();
            }

            ViewBag.RelatedBlogs = _blogService.GetRelatedBlogsByCatId(blog.CategoryId);
            ViewBag.CurrentBlogId = blog.BlogId;

            return View(blog);
        }

        #endregion

        #region Blog Comment

        [Authorize]
        [HttpPost]
        public IActionResult CreateComment(Comment comment)
        {
            comment.UserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            comment.CommentCreateDate = DateTime.Now;
            comment.IsDelete = false;

            _commentService.AddComment(comment);

            return View("ShowComment", _commentService.GetCommentsByBlogId(comment.BlogId));
        }

        public IActionResult ShowComment(int id, int pageNum = 1) // id = blogId
        {
            return View(_commentService.GetCommentsByBlogId(id, pageNum));
        }

        #region Delete Comment

        [Authorize]
        public IActionResult DeleteComment(int id,int blogId) // id = comment id
        {
            _commentService.DeleteCommentById(id);

            return Redirect("/Blogs/" + blogId);
        }

        #endregion

        #region Answer Comment

        [Authorize]
        public IActionResult CreateAnswer(int id, string body) // id = comment id
        {
            if (!string.IsNullOrEmpty(body))
            {
                var sanitizer = new HtmlSanitizer();
                body = sanitizer.Sanitize(body);

                CommentAnswer answer = new CommentAnswer()
                {
                    AnswerBody = body,
                    CommentId = id,
                    CreateDate = DateTime.Now,
                    IsDelete = false,
                    UserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString())
                };

                int answerId = _commentService.AddAnswer(answer);

                int blogId = _commentService.GetBlogIdByCommentAnswerId(answerId);

                return Redirect("/Blogs/" + blogId);
            }

            return Forbid();
        }

        [Authorize]
        public IActionResult DeleteAnswer(int id , int blogId) // id = comment answer id
        {
            // way 1 :
            //int blogId = _commentService.GetBlogIdByCommentAnswerId(id);

            // way 2 :
            _commentService.DeleteAnswerById(id);

            return Redirect("/Blogs/" + blogId);
        }
        #endregion

        #endregion

    }
}

ShoraaDahak.Web/Pages/Admin/Blogs/CreateBlog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShoraaDahak.Core.Services.Interfaces;
using ShoraaDahak.DataLayer.Models.Blog;

namespace ShoraaDahak.Web.Pages.Admin.Blogs
{
    public class CreateBlogModel : PageModel
    {
        private readonly IBlogService _blogService;

        public CreateBlogModel(IBlogService blogService)
        {
            _blogService = blogService;
        }

        [BindProperty]
        public Blog Blog { get; set; }

        public IActionResult OnGet()
        {
            #region Fill Drop Downs

            var categories = _blogService.GetCategories();
            ViewData["Category"] = new SelectList(categories, "Value", "Text");

            var subCat = _blogService.GetSubCats(int.Parse(categories.First().Value));
            ViewData["SubCat"] = new SelectList(subCat, "Value", "Text");

            var writer = _blogService.GetWriters();
            ViewData["Writer"] = new SelectList(writer, "Value", "Text");

            var gender = _blogService.GetGenders();
            ViewData["Gender"] = new SelectList(gender, "Value", "Text");


            #endregion

            return Page();
        }

        public IActionResult OnPost(IFormFile imgBlogUp)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _blogService.AddBlog(Blog,imgBlogUp);

            return RedirectToPage("Index");
        }
    }
}

ShoraaDahak.Web/Pages/Admin/Blogs/EditBlog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShoraaDahak.Core.Services.Interfaces;
using ShoraaDahak.DataLayer.Models.Blog;

namespace ShoraaDahak.Web.Pages.Admin.Blogs
{
    public class EditBlogModel : PageModel
    {
        private readonly IBlogService _blogService;

        public EditBlogModel(IBlogService blogService)
        {
            _blogService = blogService;
        }

        [BindProperty]
        public Blog Blog { get; set; }

        public IActionResult OnGet(int id)
        {
            Blog = _blogService.GetBlogById(id);

            #region Fill Drop Downs

            var categories = _blogService.GetCategories();
            ViewData["Category"] = new SelectList(categories, "Value", "Text");

            var subCat = _blogService.GetSubCats(Blog.CategoryId);
            ViewData["SubCat"] = new SelectList(subCat, "Value", "Text");

            var writer = _blogService.GetWriters();
            ViewData["Writer"] = new SelectList(writer, "Value", "Text");

            var gender = _blogService.GetGenders();
            ViewData["Gender"] = new SelectList(gender, "Value", "Text");


            #endregion

            return Page();
        }

        public IActionResult OnPost(IFormFile imgBlogUp)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _blogService.UpdateBlog(Blog, imgBlogUp);

            return RedirectToPage("Index");
        }
    }
}

ShoraaDahak.Web/Pages/Admin/Blogs/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShoraaDahak.Core.Consts;
using ShoraaDahak.Core.DTOs;
using ShoraaDahak.Core.Services.Interfaces;

namespace ShoraaDahak.Web.Pages.Admin.Blogs
{
    public class IndexModel : PageModel
    {
        private readonly IBlogService _blogService;

        public IndexModel(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public List<BlogsForAdminIndexViewModel> Blogs { get; set; }

        public IActionResult OnGet()
        {
            Blogs = _blogService.GetBlogsForShowInIndexAdmin();

            ViewData["BlogByMans"] = Blogs.Count(b => b.GenderId == Gender.Man);
            ViewData["BlogByWomen"] = Blogs.Count(b => b.GenderId == Gender.Woman);

            return Page();
        }

        public IActionResult OnGetDeleteBlog(int id)
        {
            _blogService.DeleteBlog(id);

            return RedirectToPage("Index");
        }
    }
}

ShoraaDahak.Web/Pages/Admin/Blogs/CreateBlog.cshtml
@page
@model ShoraaDahak.Web.Pages.Admin.Blogs.CreateBlogModel
@{
    ViewData["Title"] = "افزودن بلاگ جدید";
}

<div class="row">
    <div class="col-lg-9">
        <h1 class="page-header">افزودن بلاگ جدید</h1>
    </div>
    <div class="col-md-3">
        <a asp-page="Index" class="btn btn-outline btn-primary">لیست بلاگ ها</a>
    </div>
</div>
<div class="row">
    <form method="post" enctype="multipart/form-data">
        <div class="col-md-7">
            <div class="panel panel-info">
                <div class="panel-heading">
                    اطلاعات بلاگ
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label>تیتر</label>
                        <input type="text" asp-for="Blog.BlogTitle" class="form-control" placeholder="تیتر بلاگ را وارد کنید ">
                        <span asp-validation-for="Blog.BlogTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>دسته بندی</label>
                        <select class="form-control" asp-for="Blog.CategoryId" asp-items="@(ViewData["Category"] as SelectList)"></select>
                        <span asp-validation-for="Blog.CategoryId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>زیر گروه</label>
                        <select class="form-control" asp-for="Blog.SubCatId" asp-items="@(ViewData["SubCat"] as SelectList)"></select>
                        <span asp-validation-for="Blog.SubCatId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>نویسنده</label>
                        <select class="form-control" asp-for="Blog.WriterId" asp-items="@(ViewData["Writer"] as SelectList)"></select>
                        <span asp-validation-for="Blog.WriterId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>جنسیت نویسنده</label>
                        <select class="form-control" asp-for="Blog.GenderId" asp-items="@(ViewData["Gender"] as SelectList)"></select>
                        <span asp-validation-for="Blog.GenderId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>توضیح کوتاه</label>
                        <textarea type="text" asp-for="Blog.LittleDescription" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Blog.LittleDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>متن بلاگ</label>
                        <textarea type="text" asp-for="Blog.BlogBody" class="form-control" rows="12"></textarea>
                        <span asp-validation-for="Blog.BlogBody" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="panel panel-success">
                <div class="panel-heading">
                    جزییات
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label>افزودن تصویر</label>
                        <input type="file" id="imgBlogUp" name="imgBlogUp">
                        <span asp-validation-for="Blog.BlogImageName" class="text-danger"></span>
                    </div>
                    <img id="imgBlg" class="img-fluid img-thumbnail" src="/img/Service/Defualt.webp" />
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <button type="submit" class="btn btn-success btn-lg btn-block">ثبت</button>
        </div>
    </form>
</div>

@section Scripts
{
    <script>
        $("#Blog_CategoryId").change(function () {
            $("#Blog_SubCatId").empty();
            $.getJSON("/HomeAdmin/GetSubCats/" + $("#Blog_CategoryId :selected").val(),
                function (data) {
                    $.each(data,
                        function () {
                            $("#Blog_SubCatId").append('<option value=' + this.value + '>' + this.text + '</option>');
                        });
                });
        });
    </script>

    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgBlg').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $("#imgBlogUp").change(function () {
            readURL(this);
        });
    </script>

    <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Blog_BlogBody', {
            customConfig: '/js/Config.js'
        });
    </script>
}

ShoraaDahak.Web/Pages/Admin/Blogs/EditBlog.cshtml
@page
@model ShoraaDahak.Web.Pages.Admin.Blogs.EditBlogModel
@{
    ViewData["Title"] = "ویرایش بلاگ";
}

<div class="row">
    <div class="col-lg-9">
        <h1 class="page-header">ویرایش بلاگ</h1>
    </div>
    <div class="col-md-3">
        <a asp-page="Index" class="btn btn-outline btn-primary">لیست بلاگ ها</a>
    </div>
</div>
<div class="row">
    <form method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="Blog.BlogId"/>
        <input type="hidden" asp-for="Blog.BlogImageName"/>
        <div class="col-md-7">
            <div class="panel panel-info">
                <div class="panel-heading">
                    اطلاعات بلاگ
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label>تیتر</label>
                        <input type="text" asp-for="Blog.BlogTitle" class="form-control" placeholder="تیتر بلاگ را وارد کنید ">
                        <span asp-validation-for="Blog.BlogTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>دسته بندی</label>
                        <select class="form-control" asp-for="Blog.CategoryId" asp-items="@(ViewData["Category"] as SelectList)"></select>
                        <span asp-validation-for="Blog.CategoryId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>زیر گروه</label>
                        <select class="form-control" asp-for="Blog.SubCatId" asp-items="@(ViewData["SubCat"] as SelectList)"></select>
                        <span asp-validation-for="Blog.SubCatId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>نویسنده</label>
                        <select class="form-control" asp-for="Blog.WriterId" asp-items="@(ViewData["Writer"] as SelectList)"></select>
                        <span asp-validation-for="Blog.WriterId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label>جنسیت نویسنده</label>
                        <select class="form-control" asp-for="Blog.GenderId" asp-items="@(ViewData["Gender"] as SelectList)"></select>
                        <span asp-validation-for="Blog.GenderId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>توضیح کوتاه</label>
                        <textarea type="text" asp-for="Blog.LittleDescription" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Blog.LittleDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>متن بلاگ</label>
                        <textarea type="text" asp-for="Blog.BlogBody" class="form-control" rows="12"></textarea>
                        <span asp-validation-for="Blog.BlogBody" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="panel panel-success">
                <div class="panel-heading">
                    جزییات
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label>افزودن تصویر</label>
                        <input type="file" id="imgBlogUp" name="imgBlogUp">
                        <span asp-validation-for="Blog.BlogImageName" class="text-danger"></span>
                    </div>
                    <img id="imgBlg" class="img-fluid img-thumbnail" src="/Blog/image/@Model.Blog.BlogImageName"/>
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <button type="submit" class="btn btn-success btn-lg btn-block">ثبت</button>
        </div>
    </form>
</div>

@section Scripts
{
    <script>
        $("#Blog_CategoryId").change(function () {
            $("#Blog_SubCatId").empty();
            $.getJSON("/HomeAdmin/GetSubCats/" + $("#Blog_CategoryId :selected").val(),
                function (data) {
                    $.each(data,
                        function () {
                            $("#Blog_SubCatId").append('<option value=' + this.value + '>' + this.text + '</option>');
                        });
                });
        });
    </script>

    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgBlg').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $("#imgBlogUp").change(function () {
            readURL(this);
        });
    </script>

    <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Blog_BlogBody', {
            customConfig: '/js/Config.js'
        });
    </script>
}

ShoraaDahak.Web/Pages/Admin/Blogs/Index.cshtml
@page
@using ShoraaDahak.Core.Convertors
@model ShoraaDahak.Web.Pages.Admin.Blogs.IndexModel
@{
    ViewData["Title"] = "لیست بلاگ ها";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">لیست بلاگ ها</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a asp-page="CreateBlog" class="btn btn-outline btn-success">افزودن بلاگ</a>
    </div>
</div>
<br />
<div class="col-md-9">
    <div class="panel panel-info">
        <div class="panel-heading">
            لیست بلاگ ها
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">
                        <thead>
                            <tr>
                                <th>تیتر</th>
                                <th>نویسنده</th>
                                <th>توضیح کوتاه</th>
                                <th>دسته بندی</th>
                                <th>دستورات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Blogs)
                                {
                                    <tr>
                                        <td>@item.Title</td>
                                        <td>@item.Writer</td>
                                        <td>@item.MiniDescription</td>
                                        <td>@item.Category</td>
                                        <td>
                                            <a asp-page="EditBlog" asp-route-Id="@item.BlogId" class="btn btn-outline btn-info btn-sm">ویرایش</a>
                                            <a asp-page-handler="DeleteBlog" onclick="return confirm('آیا از حذف این بلاگ مطمعن هستید ؟')" asp-route-Id="@item.BlogId" class="btn btn-outline btn-danger btn-sm">حذف</a>
                                        </td>
                                    </tr>
                                }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-12 col-md-3">
    <div class="panel panel-success">
        <div class="panel-heading">
            <i class="fa fa-bell fa-fw"></i>  آمار بخش بلاگ ها
        </div>
        <div class="panel-body">
            <div class="list-group">
                <a class="list-group-item">
                    <i class="fa fa-question"></i> بلاگ های ثبت شده توسط آقایان
                    <span class="pull-left text-info small">
                        <em>@ViewData["BlogByMans"] مورد</em>
                    </span>
                </a>
                <a class="list-group-item">
                    <i class="fa fa-react"></i> بلاگ های ثبت شده توسط خانم ها
                    <span class="pull-left text-muted small">
                        <em class="txtpurp">@ViewData["BlogByWomen"] مورد </em>
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>